const fs = require("fs");
require("dotenv").config();

const filePath = "dist/index.js";

const errorCode = `
var HapticaExtensionError = (function (_super) {
  __extends(HapticaExtensionError, _super);
  function HapticaExtensionError(message) {
    return _super.call(this, message) || this;
  }
  return HapticaExtensionError;
}(Error));
`;

try {
  let content = fs.readFileSync(filePath, "utf8");
  content =
    "// Generated by the haptica-kit npm package: https://github.com/mhayes853/HapticaKit.\n" +
    content;
  content = content.replace(/exports\..*;/gm, "");
  const symbol = 'Symbol._hapticaPrivate = Symbol("_hapticaPrivate");';
  content = content.replace(symbol, symbol + errorCode);
  content = content.replace(
    'Object.defineProperty(exports, "__esModule", { value: true });',
    "",
  );
  fs.writeFileSync(
    process.env.JS_CORIFY_PATH ?? "dist/js-corified.js",
    content,
  );
  console.log("JSCorified Successfully");
} catch (err) {
  console.error("Error processing file:", err);
}
